### ISSUE TITLE
can't enter setup code for accessory

### ISSUE THREAD

**Issue by hg111** [fredericfalliere/HomeKit#2]
This is probably on Apple's side in Homekit, but I'm wondering if you didn't run into it or how did you go about fixing it?

when I try your demo, 'addAccessory()' won't allow entering the setup code (typically generated by 'Homekit Accessory Simulator') inside the designated  text field.

Any thoughts? I'll be interested in exploring your demo some more, but can't get pass this error...

thanks,

hg111

**Comment by fredericfalliere** [comment]
Does the keyboard show ? I had trouble with the new iOS simulator, the software keyboard was by default hidden. It's in the hardware menu. Try playing with the option, it was kind of buggy in beta 2 and 3. Good luck !

**Comment by hg111** [comment]
Yes, that was it!! I was able to register the accessory on the simulator. Still can't get it on the phone though. The pop-up for setup code isn't  showing (is it because it is already registered?) and getting "Accessory pairing failed". 

I'm wondering if this because the iPhone can't locate a physical accessory with BLuetooth? Do I need to sign up for the MFI program? It seems that it retained the home and room information. 

Really appreciate your help,

Thanks

Haggai
