### ISSUE TITLE
won't allow to add accessory on an iPhone (4s) 

### ISSUE THREAD

**Issue by hg111** [fredericfalliere/HomeKit#3]
It works for me on the IOS simulator (thanks!), but when running on the iPhone, I can't get the popup for the setup code of the accessory, which in turn causes it to fail in 'addDiscovery' (my guess) It sounds like it should work if you got it to work with Siri? Can you explain further?

Thank you in advance,

hg

**Comment by fredericfalliere** [comment]
Try updating your iOS to newer versions ... This popup is managed by the OS not by the app dev.
