### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by incipio-swetha** [fredericfalliere/HomeKit#4]
Hi,

The app is running on simulator, but when I install the app on iPod touch 5 with iOS 8 (Beta version), the app crashes. Any solution is appreciated.

Thanks,
Swetha.

**Comment by elvisimprsntr** [comment]
Try GM seed

Are you a registered developer with a provisioning file and certificate?

E

edit:removed not legit link

**Comment by fredericfalliere** [comment]
@incipio-swetha what's the log output ?

**Comment by incipio-swetha** [comment]
Hi,

I downloaded the latest iOS 8 GM seed and I am using a valid enterprise certificate.
